version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    groups:
      actions:
        patterns: ['*']
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: docker
      include: scope
